### ISSUE TITLE
Section-two div responsiveness issues

### ISSUE THREAD

**Issue by SurlyMae** [fee-slc-2016/tiy-slc-fee-2016#3]
circle-pics are overflowing parent when resizing

**Comment by DrewWarrenTIY** [comment]
Hey Ash, since your team has some members who are already experienced with bootstrap, did y'all want to tackle rewriting the HTML/CSS in bootstrap?

We are just trying to come up with some issues, so we are tabling any issue of rewriting with bootstrap for now. - Ash

**Comment by DrewWarrenTIY** [comment]
If someone tries to fix the Circle-pic issue now and we decide to implement bootstrap later, that will be wasted effort.

We are continuing with flexbox now, since we feel we need to know it better - if later, group decides to move to Bootstrap, that'll be a good thing to learn too - Ash

**Comment by kfurness** [comment]
We are working on a version with bootstrap. Feel free to do your own bootstrap version or continue with flexbox.

**Comment by DrewWarrenTIY** [comment]
Hey Ash, if you actually make a new comment instead of editing an old one, then the updated number of comments will indicate that a response has been given. If you edit the comments instead, it's impossible to know when a change has been made/response has been given unless you open it up and check to see if the contents have been edited. Just some food for thought!

**Comment by trrapp12** [comment]
So if you decide to go ahead with Bootstrap it needs to be unanimous among the groups or else everything will break when we have to merge our projects.

Please see #13 Styleguide

**Comment by JoniWeiss** [comment]
Resolved with 6782279 merge request.
